FROM python:2.7.17-buster
RUN apt-get update && yes | apt-get upgrade
RUN mkdir -p /models
RUN apt-get install -y git python-pip
RUN pip install --upgrade pip
RUN python --version
RUN pip --version

COPY . /nsm
WORKDIR /nsm
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
CMD python setup.py develop
